{
 "title": "COVID-19",
 "time": { "from": "2020-01-21T05:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "label": "Show:", "query": "Confirmed, Deaths, Recovered" }
  ]
 },
 "panels": [
  {
   "title": "Total $Type by Country",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "cases" }
   ],
   "targets": [
    {
     "alias": "[[tag_Country/Region]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country/Region" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "people",
     "query": "SELECT sum(\"value\") FROM \"people\" WHERE (\"type\" =~ /^$Type$/) AND $timeFilter GROUP BY time($__interval), \"Country/Region\", \"type\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^$Type$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily $Type by Country",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "locale", "label": "cases" }
   ],
   "targets": [
    {
     "alias": "[[tag_Country/Region]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country/Region" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "people",
     "query": "SELECT difference(max(\"value\")) FROM \"people\" WHERE (\"type\" =~ /^$Type$/) AND $timeFilter GROUP BY \"Country/Region\", \"type\", time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^$Type$/" }
     ]
    }
   ]
  },
  {
   "title": "Total $Type by Region",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale", "label": "cases" }
   ],
   "targets": [
    {
     "alias": "[[tag_Country/Region]]/[[tag_Province/State]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country/Region" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "Province/State" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "people",
     "query": "SELECT sum(\"value\") FROM \"people\" WHERE (\"type\" =~ /^$Type$/) AND $timeFilter GROUP BY time($__interval), \"Country/Region\", \"type\", \"Province/State\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^$Type$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily $Type by Region",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "locale", "label": "cases" }
   ],
   "targets": [
    {
     "alias": "[[tag_Country/Region]]/[[tag_Province/State]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Country/Region" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "Province/State" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "people",
     "query": "SELECT difference(max(\"value\")) FROM \"people\" WHERE (\"type\" =~ /^$Type$/) AND $timeFilter GROUP BY \"Country/Region\", \"Province/State\", \"type\", time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=~", "value": "/^$Type$/" }
     ]
    }
   ]
  }
 ]
}